title: Pattern Kit

paths:
  data:
    - /resources/fixtures
  test_data:
    - /resources/fixtures
  schemas:
    - /resources/fixtures
  templates:
    - /resources/fixtures
  docs:
    - /resources/fixtures
  sg:
    - /resources/fixtures
extensions:
  data: .docs.json
  test_data: .test.json
  schemas: .json
  templates: .twig
  docs: .docs.md
  sg: .sg.md
categories:
    - Pattern
    - Sub Pattern
    - Layout
    - Component
    - Atom
assets:
  css:
  js:
  footer_js:
dev: true

